# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock.xci
# IP: The module: 'mmcm_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: Z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock.xci
# IP: The module: 'mmcm_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/memsMicRec_vivado/memsMicRec_vivado.srcs/sources_1/ip/mmcm_clock/mmcm_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
