set_property SRC_FILE_INFO {cfile:Z:/Documents/DOCS/projects/projects_uploaded/PN004_mems_mic_recorder/fpga_project/code/Basys3_Master.xdc rfile:../../../../code/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports SCLK]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports CS_N]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports MOSI]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports MISO]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports CLK_PDM_HD]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports PDM_DATA_IN]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks sys_clk_pin] -to [get_clocks -of_objects [get_pins clocking_comp/mmcm_clocks/inst/mmcm_adv_inst/CLKOUT0]]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins clocking_comp/mmcm_clocks/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks sys_clk_pin]
